---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: etok
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: etok
subjects:
- kind: ServiceAccount
  name: etok
  namespace: etok
