apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook
rules:
# Webhook needs to create configmaps, in which to store terraform configuration for a run
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
# Webhook needs to be able to create and monitor runs
- apiGroups:
  - etok.dev
  resources:
  - runs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - etok.dev
  resources:
  - runs/status
  verbs:
  - get
  - patch
  - update
# Webhook needs read-access to workspaces
- apiGroups:
  - etok.dev
  resources:
  - workspaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - etok.dev
  resources:
  - workspaces/status
  verbs:
  - get
  - patch
  - update
