
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: webhook
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods/logs
  verbs:
  - get
- apiGroups:
  - etok.dev
  resources:
  - checkruns
  verbs:
  - create
  - get
  - patch
  - update
- apiGroups:
  - etok.dev
  resources:
  - checksuites
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - etok.dev
  resources:
  - runs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - etok.dev
  resources:
  - workspaces
  verbs:
  - get
  - list
