// Copyright © 2020 Louis Garman <louisgarman@gmail.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTaints implements TaintInterface
type FakeTaints struct {
	Fake *FakeStokV1alpha1
	ns   string
}

var taintsResource = schema.GroupVersionResource{Group: "stok.goalspike.com", Version: "v1alpha1", Resource: "taints"}

var taintsKind = schema.GroupVersionKind{Group: "stok.goalspike.com", Version: "v1alpha1", Kind: "Taint"}

// Get takes name of the taint, and returns the corresponding taint object, and an error if there is any.
func (c *FakeTaints) Get(name string, options v1.GetOptions) (result *v1alpha1.Taint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(taintsResource, c.ns, name), &v1alpha1.Taint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Taint), err
}

// List takes label and field selectors, and returns the list of Taints that match those selectors.
func (c *FakeTaints) List(opts v1.ListOptions) (result *v1alpha1.TaintList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(taintsResource, taintsKind, c.ns, opts), &v1alpha1.TaintList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TaintList{ListMeta: obj.(*v1alpha1.TaintList).ListMeta}
	for _, item := range obj.(*v1alpha1.TaintList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested taints.
func (c *FakeTaints) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(taintsResource, c.ns, opts))

}

// Create takes the representation of a taint and creates it.  Returns the server's representation of the taint, and an error, if there is any.
func (c *FakeTaints) Create(taint *v1alpha1.Taint) (result *v1alpha1.Taint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(taintsResource, c.ns, taint), &v1alpha1.Taint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Taint), err
}

// Update takes the representation of a taint and updates it. Returns the server's representation of the taint, and an error, if there is any.
func (c *FakeTaints) Update(taint *v1alpha1.Taint) (result *v1alpha1.Taint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(taintsResource, c.ns, taint), &v1alpha1.Taint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Taint), err
}

// Delete takes name of the taint and deletes it. Returns an error if one occurs.
func (c *FakeTaints) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(taintsResource, c.ns, name), &v1alpha1.Taint{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTaints) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(taintsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.TaintList{})
	return err
}

// Patch applies the patch and returns the patched taint.
func (c *FakeTaints) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Taint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(taintsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Taint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Taint), err
}
