// Copyright © 2020 Louis Garman <louisgarman@gmail.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeShows implements ShowInterface
type FakeShows struct {
	Fake *FakeStokV1alpha1
	ns   string
}

var showsResource = schema.GroupVersionResource{Group: "stok.goalspike.com", Version: "v1alpha1", Resource: "shows"}

var showsKind = schema.GroupVersionKind{Group: "stok.goalspike.com", Version: "v1alpha1", Kind: "Show"}

// Get takes name of the show, and returns the corresponding show object, and an error if there is any.
func (c *FakeShows) Get(name string, options v1.GetOptions) (result *v1alpha1.Show, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(showsResource, c.ns, name), &v1alpha1.Show{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Show), err
}

// List takes label and field selectors, and returns the list of Shows that match those selectors.
func (c *FakeShows) List(opts v1.ListOptions) (result *v1alpha1.ShowList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(showsResource, showsKind, c.ns, opts), &v1alpha1.ShowList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ShowList{ListMeta: obj.(*v1alpha1.ShowList).ListMeta}
	for _, item := range obj.(*v1alpha1.ShowList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested shows.
func (c *FakeShows) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(showsResource, c.ns, opts))

}

// Create takes the representation of a show and creates it.  Returns the server's representation of the show, and an error, if there is any.
func (c *FakeShows) Create(show *v1alpha1.Show) (result *v1alpha1.Show, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(showsResource, c.ns, show), &v1alpha1.Show{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Show), err
}

// Update takes the representation of a show and updates it. Returns the server's representation of the show, and an error, if there is any.
func (c *FakeShows) Update(show *v1alpha1.Show) (result *v1alpha1.Show, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(showsResource, c.ns, show), &v1alpha1.Show{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Show), err
}

// Delete takes name of the show and deletes it. Returns an error if one occurs.
func (c *FakeShows) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(showsResource, c.ns, name), &v1alpha1.Show{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeShows) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(showsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ShowList{})
	return err
}

// Patch applies the patch and returns the patched show.
func (c *FakeShows) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Show, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(showsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Show{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Show), err
}
