// Copyright © 2020 Louis Garman <louisgarman@gmail.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeShells implements ShellInterface
type FakeShells struct {
	Fake *FakeStokV1alpha1
	ns   string
}

var shellsResource = schema.GroupVersionResource{Group: "stok.goalspike.com", Version: "v1alpha1", Resource: "shells"}

var shellsKind = schema.GroupVersionKind{Group: "stok.goalspike.com", Version: "v1alpha1", Kind: "Shell"}

// Get takes name of the shell, and returns the corresponding shell object, and an error if there is any.
func (c *FakeShells) Get(name string, options v1.GetOptions) (result *v1alpha1.Shell, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(shellsResource, c.ns, name), &v1alpha1.Shell{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Shell), err
}

// List takes label and field selectors, and returns the list of Shells that match those selectors.
func (c *FakeShells) List(opts v1.ListOptions) (result *v1alpha1.ShellList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(shellsResource, shellsKind, c.ns, opts), &v1alpha1.ShellList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ShellList{ListMeta: obj.(*v1alpha1.ShellList).ListMeta}
	for _, item := range obj.(*v1alpha1.ShellList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested shells.
func (c *FakeShells) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(shellsResource, c.ns, opts))

}

// Create takes the representation of a shell and creates it.  Returns the server's representation of the shell, and an error, if there is any.
func (c *FakeShells) Create(shell *v1alpha1.Shell) (result *v1alpha1.Shell, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(shellsResource, c.ns, shell), &v1alpha1.Shell{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Shell), err
}

// Update takes the representation of a shell and updates it. Returns the server's representation of the shell, and an error, if there is any.
func (c *FakeShells) Update(shell *v1alpha1.Shell) (result *v1alpha1.Shell, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(shellsResource, c.ns, shell), &v1alpha1.Shell{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Shell), err
}

// Delete takes name of the shell and deletes it. Returns an error if one occurs.
func (c *FakeShells) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(shellsResource, c.ns, name), &v1alpha1.Shell{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeShells) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(shellsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ShellList{})
	return err
}

// Patch applies the patch and returns the patched shell.
func (c *FakeShells) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Shell, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(shellsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Shell{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Shell), err
}
