// Copyright © 2020 Louis Garman <louisgarman@gmail.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeForceUnlocks implements ForceUnlockInterface
type FakeForceUnlocks struct {
	Fake *FakeStokV1alpha1
	ns   string
}

var forceunlocksResource = schema.GroupVersionResource{Group: "stok.goalspike.com", Version: "v1alpha1", Resource: "forceunlocks"}

var forceunlocksKind = schema.GroupVersionKind{Group: "stok.goalspike.com", Version: "v1alpha1", Kind: "ForceUnlock"}

// Get takes name of the forceUnlock, and returns the corresponding forceUnlock object, and an error if there is any.
func (c *FakeForceUnlocks) Get(name string, options v1.GetOptions) (result *v1alpha1.ForceUnlock, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(forceunlocksResource, c.ns, name), &v1alpha1.ForceUnlock{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ForceUnlock), err
}

// List takes label and field selectors, and returns the list of ForceUnlocks that match those selectors.
func (c *FakeForceUnlocks) List(opts v1.ListOptions) (result *v1alpha1.ForceUnlockList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(forceunlocksResource, forceunlocksKind, c.ns, opts), &v1alpha1.ForceUnlockList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ForceUnlockList{ListMeta: obj.(*v1alpha1.ForceUnlockList).ListMeta}
	for _, item := range obj.(*v1alpha1.ForceUnlockList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested forceUnlocks.
func (c *FakeForceUnlocks) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(forceunlocksResource, c.ns, opts))

}

// Create takes the representation of a forceUnlock and creates it.  Returns the server's representation of the forceUnlock, and an error, if there is any.
func (c *FakeForceUnlocks) Create(forceUnlock *v1alpha1.ForceUnlock) (result *v1alpha1.ForceUnlock, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(forceunlocksResource, c.ns, forceUnlock), &v1alpha1.ForceUnlock{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ForceUnlock), err
}

// Update takes the representation of a forceUnlock and updates it. Returns the server's representation of the forceUnlock, and an error, if there is any.
func (c *FakeForceUnlocks) Update(forceUnlock *v1alpha1.ForceUnlock) (result *v1alpha1.ForceUnlock, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(forceunlocksResource, c.ns, forceUnlock), &v1alpha1.ForceUnlock{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ForceUnlock), err
}

// Delete takes name of the forceUnlock and deletes it. Returns an error if one occurs.
func (c *FakeForceUnlocks) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(forceunlocksResource, c.ns, name), &v1alpha1.ForceUnlock{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeForceUnlocks) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(forceunlocksResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ForceUnlockList{})
	return err
}

// Patch applies the patch and returns the patched forceUnlock.
func (c *FakeForceUnlocks) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ForceUnlock, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(forceunlocksResource, c.ns, name, pt, data, subresources...), &v1alpha1.ForceUnlock{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ForceUnlock), err
}
