// Copyright © 2020 Louis Garman <louisgarman@gmail.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVersions implements VersionInterface
type FakeVersions struct {
	Fake *FakeStokV1alpha1
	ns   string
}

var versionsResource = schema.GroupVersionResource{Group: "stok.goalspike.com", Version: "v1alpha1", Resource: "versions"}

var versionsKind = schema.GroupVersionKind{Group: "stok.goalspike.com", Version: "v1alpha1", Kind: "Version"}

// Get takes name of the version, and returns the corresponding version object, and an error if there is any.
func (c *FakeVersions) Get(name string, options v1.GetOptions) (result *v1alpha1.Version, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(versionsResource, c.ns, name), &v1alpha1.Version{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Version), err
}

// List takes label and field selectors, and returns the list of Versions that match those selectors.
func (c *FakeVersions) List(opts v1.ListOptions) (result *v1alpha1.VersionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(versionsResource, versionsKind, c.ns, opts), &v1alpha1.VersionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VersionList{ListMeta: obj.(*v1alpha1.VersionList).ListMeta}
	for _, item := range obj.(*v1alpha1.VersionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested versions.
func (c *FakeVersions) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(versionsResource, c.ns, opts))

}

// Create takes the representation of a version and creates it.  Returns the server's representation of the version, and an error, if there is any.
func (c *FakeVersions) Create(version *v1alpha1.Version) (result *v1alpha1.Version, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(versionsResource, c.ns, version), &v1alpha1.Version{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Version), err
}

// Update takes the representation of a version and updates it. Returns the server's representation of the version, and an error, if there is any.
func (c *FakeVersions) Update(version *v1alpha1.Version) (result *v1alpha1.Version, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(versionsResource, c.ns, version), &v1alpha1.Version{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Version), err
}

// Delete takes name of the version and deletes it. Returns an error if one occurs.
func (c *FakeVersions) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(versionsResource, c.ns, name), &v1alpha1.Version{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVersions) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(versionsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.VersionList{})
	return err
}

// Patch applies the patch and returns the patched version.
func (c *FakeVersions) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Version, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(versionsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Version{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Version), err
}
