// Code generated by go generate; DO NOT EDIT.
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// Imp is the Schema for the imports API
// +kubebuilder:subresource:status
// +kubebuilder:resource:path=imports,scope=Namespaced
// +genclient
type Imp struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	CommandSpec   `json:"spec,omitempty"`
	CommandStatus `json:"status,omitempty"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// ImpList contains a list of Imp
type ImpList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Imp `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Imp{}, &ImpList{})
}
