// Code generated by go generate; DO NOT EDIT.
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// Refresh is the Schema for the refreshs API
// +kubebuilder:subresource:status
// +kubebuilder:resource:path=refreshs,scope=Namespaced
// +genclient
type Refresh struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	CommandSpec   `json:"spec,omitempty"`
	CommandStatus `json:"status,omitempty"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// RefreshList contains a list of Refresh
type RefreshList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Refresh `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Refresh{}, &RefreshList{})
}
