// Code generated by go generate; DO NOT EDIT.
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// Untaint is the Schema for the untaints API
// +kubebuilder:subresource:status
// +kubebuilder:resource:path=untaints,scope=Namespaced
// +genclient
type Untaint struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	CommandSpec   `json:"spec,omitempty"`
	CommandStatus `json:"status,omitempty"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// UntaintList contains a list of Untaint
type UntaintList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Untaint `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Untaint{}, &UntaintList{})
}
