// Copyright © 2020 Louis Garman <louisgarman@gmail.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	scheme "github.com/leg100/stok/pkg/client/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AppliesGetter has a method to return a ApplyInterface.
// A group's client should implement this interface.
type AppliesGetter interface {
	Applies(namespace string) ApplyInterface
}

// ApplyInterface has methods to work with Apply resources.
type ApplyInterface interface {
	Create(*v1alpha1.Apply) (*v1alpha1.Apply, error)
	Update(*v1alpha1.Apply) (*v1alpha1.Apply, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Apply, error)
	List(opts v1.ListOptions) (*v1alpha1.ApplyList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Apply, err error)
	ApplyExpansion
}

// applies implements ApplyInterface
type applies struct {
	client rest.Interface
	ns     string
}

// newApplies returns a Applies
func newApplies(c *StokV1alpha1Client, namespace string) *applies {
	return &applies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the apply, and returns the corresponding apply object, and an error if there is any.
func (c *applies) Get(name string, options v1.GetOptions) (result *v1alpha1.Apply, err error) {
	result = &v1alpha1.Apply{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("applies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Applies that match those selectors.
func (c *applies) List(opts v1.ListOptions) (result *v1alpha1.ApplyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ApplyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("applies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested applies.
func (c *applies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("applies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a apply and creates it.  Returns the server's representation of the apply, and an error, if there is any.
func (c *applies) Create(apply *v1alpha1.Apply) (result *v1alpha1.Apply, err error) {
	result = &v1alpha1.Apply{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("applies").
		Body(apply).
		Do().
		Into(result)
	return
}

// Update takes the representation of a apply and updates it. Returns the server's representation of the apply, and an error, if there is any.
func (c *applies) Update(apply *v1alpha1.Apply) (result *v1alpha1.Apply, err error) {
	result = &v1alpha1.Apply{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("applies").
		Name(apply.Name).
		Body(apply).
		Do().
		Into(result)
	return
}

// Delete takes name of the apply and deletes it. Returns an error if one occurs.
func (c *applies) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("applies").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *applies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("applies").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched apply.
func (c *applies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Apply, err error) {
	result = &v1alpha1.Apply{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("applies").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
