// Copyright © 2020 Louis Garman <louisgarman@gmail.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	scheme "github.com/leg100/stok/pkg/client/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DestroysGetter has a method to return a DestroyInterface.
// A group's client should implement this interface.
type DestroysGetter interface {
	Destroys(namespace string) DestroyInterface
}

// DestroyInterface has methods to work with Destroy resources.
type DestroyInterface interface {
	Create(*v1alpha1.Destroy) (*v1alpha1.Destroy, error)
	Update(*v1alpha1.Destroy) (*v1alpha1.Destroy, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Destroy, error)
	List(opts v1.ListOptions) (*v1alpha1.DestroyList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Destroy, err error)
	DestroyExpansion
}

// destroys implements DestroyInterface
type destroys struct {
	client rest.Interface
	ns     string
}

// newDestroys returns a Destroys
func newDestroys(c *StokV1alpha1Client, namespace string) *destroys {
	return &destroys{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the destroy, and returns the corresponding destroy object, and an error if there is any.
func (c *destroys) Get(name string, options v1.GetOptions) (result *v1alpha1.Destroy, err error) {
	result = &v1alpha1.Destroy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("destroys").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Destroys that match those selectors.
func (c *destroys) List(opts v1.ListOptions) (result *v1alpha1.DestroyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.DestroyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("destroys").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested destroys.
func (c *destroys) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("destroys").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a destroy and creates it.  Returns the server's representation of the destroy, and an error, if there is any.
func (c *destroys) Create(destroy *v1alpha1.Destroy) (result *v1alpha1.Destroy, err error) {
	result = &v1alpha1.Destroy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("destroys").
		Body(destroy).
		Do().
		Into(result)
	return
}

// Update takes the representation of a destroy and updates it. Returns the server's representation of the destroy, and an error, if there is any.
func (c *destroys) Update(destroy *v1alpha1.Destroy) (result *v1alpha1.Destroy, err error) {
	result = &v1alpha1.Destroy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("destroys").
		Name(destroy.Name).
		Body(destroy).
		Do().
		Into(result)
	return
}

// Delete takes name of the destroy and deletes it. Returns an error if one occurs.
func (c *destroys) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("destroys").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *destroys) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("destroys").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched destroy.
func (c *destroys) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Destroy, err error) {
	result = &v1alpha1.Destroy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("destroys").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
