// Copyright © 2020 Louis Garman <louisgarman@gmail.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type ApplyExpansion interface{}

type DestroyExpansion interface{}

type ForceUnlockExpansion interface{}

type GetExpansion interface{}

type ImpExpansion interface{}

type InitExpansion interface{}

type OutputExpansion interface{}

type PlanExpansion interface{}

type RefreshExpansion interface{}

type ShellExpansion interface{}

type ShowExpansion interface{}

type StateExpansion interface{}

type TaintExpansion interface{}

type UntaintExpansion interface{}

type ValidateExpansion interface{}

type WorkspaceExpansion interface{}
