// Copyright © 2020 Louis Garman <louisgarman@gmail.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	scheme "github.com/leg100/stok/pkg/client/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// InitsGetter has a method to return a InitInterface.
// A group's client should implement this interface.
type InitsGetter interface {
	Inits(namespace string) InitInterface
}

// InitInterface has methods to work with Init resources.
type InitInterface interface {
	Create(*v1alpha1.Init) (*v1alpha1.Init, error)
	Update(*v1alpha1.Init) (*v1alpha1.Init, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Init, error)
	List(opts v1.ListOptions) (*v1alpha1.InitList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Init, err error)
	InitExpansion
}

// inits implements InitInterface
type inits struct {
	client rest.Interface
	ns     string
}

// newInits returns a Inits
func newInits(c *StokV1alpha1Client, namespace string) *inits {
	return &inits{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the init, and returns the corresponding init object, and an error if there is any.
func (c *inits) Get(name string, options v1.GetOptions) (result *v1alpha1.Init, err error) {
	result = &v1alpha1.Init{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("inits").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Inits that match those selectors.
func (c *inits) List(opts v1.ListOptions) (result *v1alpha1.InitList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.InitList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("inits").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested inits.
func (c *inits) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("inits").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a init and creates it.  Returns the server's representation of the init, and an error, if there is any.
func (c *inits) Create(init *v1alpha1.Init) (result *v1alpha1.Init, err error) {
	result = &v1alpha1.Init{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("inits").
		Body(init).
		Do().
		Into(result)
	return
}

// Update takes the representation of a init and updates it. Returns the server's representation of the init, and an error, if there is any.
func (c *inits) Update(init *v1alpha1.Init) (result *v1alpha1.Init, err error) {
	result = &v1alpha1.Init{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("inits").
		Name(init.Name).
		Body(init).
		Do().
		Into(result)
	return
}

// Delete takes name of the init and deletes it. Returns an error if one occurs.
func (c *inits) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("inits").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *inits) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("inits").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched init.
func (c *inits) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Init, err error) {
	result = &v1alpha1.Init{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("inits").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
