// Copyright © 2020 Louis Garman <louisgarman@gmail.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	scheme "github.com/leg100/stok/pkg/client/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PlansGetter has a method to return a PlanInterface.
// A group's client should implement this interface.
type PlansGetter interface {
	Plans(namespace string) PlanInterface
}

// PlanInterface has methods to work with Plan resources.
type PlanInterface interface {
	Create(*v1alpha1.Plan) (*v1alpha1.Plan, error)
	Update(*v1alpha1.Plan) (*v1alpha1.Plan, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Plan, error)
	List(opts v1.ListOptions) (*v1alpha1.PlanList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Plan, err error)
	PlanExpansion
}

// plans implements PlanInterface
type plans struct {
	client rest.Interface
	ns     string
}

// newPlans returns a Plans
func newPlans(c *StokV1alpha1Client, namespace string) *plans {
	return &plans{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the plan, and returns the corresponding plan object, and an error if there is any.
func (c *plans) Get(name string, options v1.GetOptions) (result *v1alpha1.Plan, err error) {
	result = &v1alpha1.Plan{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("plans").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Plans that match those selectors.
func (c *plans) List(opts v1.ListOptions) (result *v1alpha1.PlanList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PlanList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("plans").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested plans.
func (c *plans) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("plans").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a plan and creates it.  Returns the server's representation of the plan, and an error, if there is any.
func (c *plans) Create(plan *v1alpha1.Plan) (result *v1alpha1.Plan, err error) {
	result = &v1alpha1.Plan{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("plans").
		Body(plan).
		Do().
		Into(result)
	return
}

// Update takes the representation of a plan and updates it. Returns the server's representation of the plan, and an error, if there is any.
func (c *plans) Update(plan *v1alpha1.Plan) (result *v1alpha1.Plan, err error) {
	result = &v1alpha1.Plan{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("plans").
		Name(plan.Name).
		Body(plan).
		Do().
		Into(result)
	return
}

// Delete takes name of the plan and deletes it. Returns an error if one occurs.
func (c *plans) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("plans").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *plans) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("plans").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched plan.
func (c *plans) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Plan, err error) {
	result = &v1alpha1.Plan{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("plans").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
