// Copyright © 2020 Louis Garman <louisgarman@gmail.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	scheme "github.com/leg100/stok/pkg/client/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// StatesGetter has a method to return a StateInterface.
// A group's client should implement this interface.
type StatesGetter interface {
	States(namespace string) StateInterface
}

// StateInterface has methods to work with State resources.
type StateInterface interface {
	Create(*v1alpha1.State) (*v1alpha1.State, error)
	Update(*v1alpha1.State) (*v1alpha1.State, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.State, error)
	List(opts v1.ListOptions) (*v1alpha1.StateList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.State, err error)
	StateExpansion
}

// states implements StateInterface
type states struct {
	client rest.Interface
	ns     string
}

// newStates returns a States
func newStates(c *StokV1alpha1Client, namespace string) *states {
	return &states{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the state, and returns the corresponding state object, and an error if there is any.
func (c *states) Get(name string, options v1.GetOptions) (result *v1alpha1.State, err error) {
	result = &v1alpha1.State{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("states").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of States that match those selectors.
func (c *states) List(opts v1.ListOptions) (result *v1alpha1.StateList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.StateList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("states").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested states.
func (c *states) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("states").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a state and creates it.  Returns the server's representation of the state, and an error, if there is any.
func (c *states) Create(state *v1alpha1.State) (result *v1alpha1.State, err error) {
	result = &v1alpha1.State{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("states").
		Body(state).
		Do().
		Into(result)
	return
}

// Update takes the representation of a state and updates it. Returns the server's representation of the state, and an error, if there is any.
func (c *states) Update(state *v1alpha1.State) (result *v1alpha1.State, err error) {
	result = &v1alpha1.State{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("states").
		Name(state.Name).
		Body(state).
		Do().
		Into(result)
	return
}

// Delete takes name of the state and deletes it. Returns an error if one occurs.
func (c *states) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("states").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *states) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("states").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched state.
func (c *states) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.State, err error) {
	result = &v1alpha1.State{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("states").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
