// Copyright © 2020 Louis Garman <louisgarman@gmail.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	scheme "github.com/leg100/stok/pkg/client/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TaintsGetter has a method to return a TaintInterface.
// A group's client should implement this interface.
type TaintsGetter interface {
	Taints(namespace string) TaintInterface
}

// TaintInterface has methods to work with Taint resources.
type TaintInterface interface {
	Create(*v1alpha1.Taint) (*v1alpha1.Taint, error)
	Update(*v1alpha1.Taint) (*v1alpha1.Taint, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Taint, error)
	List(opts v1.ListOptions) (*v1alpha1.TaintList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Taint, err error)
	TaintExpansion
}

// taints implements TaintInterface
type taints struct {
	client rest.Interface
	ns     string
}

// newTaints returns a Taints
func newTaints(c *StokV1alpha1Client, namespace string) *taints {
	return &taints{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the taint, and returns the corresponding taint object, and an error if there is any.
func (c *taints) Get(name string, options v1.GetOptions) (result *v1alpha1.Taint, err error) {
	result = &v1alpha1.Taint{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("taints").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Taints that match those selectors.
func (c *taints) List(opts v1.ListOptions) (result *v1alpha1.TaintList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.TaintList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("taints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested taints.
func (c *taints) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("taints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a taint and creates it.  Returns the server's representation of the taint, and an error, if there is any.
func (c *taints) Create(taint *v1alpha1.Taint) (result *v1alpha1.Taint, err error) {
	result = &v1alpha1.Taint{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("taints").
		Body(taint).
		Do().
		Into(result)
	return
}

// Update takes the representation of a taint and updates it. Returns the server's representation of the taint, and an error, if there is any.
func (c *taints) Update(taint *v1alpha1.Taint) (result *v1alpha1.Taint, err error) {
	result = &v1alpha1.Taint{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("taints").
		Name(taint.Name).
		Body(taint).
		Do().
		Into(result)
	return
}

// Delete takes name of the taint and deletes it. Returns an error if one occurs.
func (c *taints) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("taints").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *taints) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("taints").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched taint.
func (c *taints) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Taint, err error) {
	result = &v1alpha1.Taint{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("taints").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
