// Copyright © 2020 Louis Garman <louisgarman@gmail.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	scheme "github.com/leg100/stok/pkg/client/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ValidatesGetter has a method to return a ValidateInterface.
// A group's client should implement this interface.
type ValidatesGetter interface {
	Validates(namespace string) ValidateInterface
}

// ValidateInterface has methods to work with Validate resources.
type ValidateInterface interface {
	Create(*v1alpha1.Validate) (*v1alpha1.Validate, error)
	Update(*v1alpha1.Validate) (*v1alpha1.Validate, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Validate, error)
	List(opts v1.ListOptions) (*v1alpha1.ValidateList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Validate, err error)
	ValidateExpansion
}

// validates implements ValidateInterface
type validates struct {
	client rest.Interface
	ns     string
}

// newValidates returns a Validates
func newValidates(c *StokV1alpha1Client, namespace string) *validates {
	return &validates{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the validate, and returns the corresponding validate object, and an error if there is any.
func (c *validates) Get(name string, options v1.GetOptions) (result *v1alpha1.Validate, err error) {
	result = &v1alpha1.Validate{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("validates").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Validates that match those selectors.
func (c *validates) List(opts v1.ListOptions) (result *v1alpha1.ValidateList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ValidateList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("validates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested validates.
func (c *validates) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("validates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a validate and creates it.  Returns the server's representation of the validate, and an error, if there is any.
func (c *validates) Create(validate *v1alpha1.Validate) (result *v1alpha1.Validate, err error) {
	result = &v1alpha1.Validate{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("validates").
		Body(validate).
		Do().
		Into(result)
	return
}

// Update takes the representation of a validate and updates it. Returns the server's representation of the validate, and an error, if there is any.
func (c *validates) Update(validate *v1alpha1.Validate) (result *v1alpha1.Validate, err error) {
	result = &v1alpha1.Validate{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("validates").
		Name(validate.Name).
		Body(validate).
		Do().
		Into(result)
	return
}

// Delete takes name of the validate and deletes it. Returns an error if one occurs.
func (c *validates) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("validates").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *validates) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("validates").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched validate.
func (c *validates) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Validate, err error) {
	result = &v1alpha1.Validate{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("validates").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
