// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"os"

	"github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	"github.com/spf13/cobra"
)

var cmdValidate = &cobra.Command{
	Use:   "validate [global flags] -- [validate args]",
	Short: "Run terraform validate",
	PreRun: validatePath,
	Run: func(cmd *cobra.Command, args []string) {
		runApp(&v1alpha1.Validate{}, "validate", DoubleDashArgsHandler(os.Args))
	},
}

func init() {
	cmdValidate.DisableFlagsInUseLine = true
	rootCmd.AddCommand(cmdValidate)
}
