// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"os"

	"github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	"github.com/spf13/cobra"
)

var cmdState = &cobra.Command{
	Use:   "state [global flags] -- [state args]",
	Short: "Run terraform state",
	Run: func(cmd *cobra.Command, args []string) {
		app := newApp("state", DoubleDashArgsHandler(os.Args))
		app.run(&v1alpha1.State{})
	},
}

func init() {
	cmdState.DisableFlagsInUseLine = true
	rootCmd.AddCommand(cmdState)
}
