// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"os"

	"github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	"github.com/spf13/cobra"
)

var cmdForceUnlock = &cobra.Command{
	Use:   "force-unlock [global flags] -- [force-unlock args]",
	Short: "Run terraform force-unlock",
	PreRun: validatePath,
	Run: func(cmd *cobra.Command, args []string) {
		runApp(&v1alpha1.ForceUnlock{}, "force-unlock", DoubleDashArgsHandler(os.Args))
	},
}

func init() {
	cmdForceUnlock.DisableFlagsInUseLine = true
	rootCmd.AddCommand(cmdForceUnlock)
}
