// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"os"

	"github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	"github.com/spf13/cobra"
)

var cmdRefresh = &cobra.Command{
	Use:   "refresh [global flags] -- [refresh args]",
	Short: "Run terraform refresh",
	PreRun: validatePath,
	Run: func(cmd *cobra.Command, args []string) {
		runApp(&v1alpha1.Refresh{}, "refresh", DoubleDashArgsHandler(os.Args))
	},
}

func init() {
	cmdRefresh.DisableFlagsInUseLine = true
	rootCmd.AddCommand(cmdRefresh)
}
