// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"os"

	"github.com/apex/log"
	"github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	"github.com/spf13/cobra"
)

var cmdDestroy = &cobra.Command{
	Use:   "destroy [global flags] -- [destroy args]",
	Short: "Run terraform destroy",
	Run: func(cmd *cobra.Command, args []string) {
		app := newApp("destroy", DoubleDashArgsHandler(os.Args))
		if err := app.run(&v1alpha1.Destroy{}); err != nil {
			log.Error(err.Error())
			os.Exit(1)
		}
	},
}

func init() {
	cmdDestroy.DisableFlagsInUseLine = true
	rootCmd.AddCommand(cmdDestroy)
}
