// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"os"

	"github.com/apex/log"
	"github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	"github.com/spf13/cobra"
)

var cmdGet = &cobra.Command{
	Use:   "get [global flags] -- [get args]",
	Short: "Run terraform get",
	Run: func(cmd *cobra.Command, args []string) {
		app := newApp("get", DoubleDashArgsHandler(os.Args))
		if err := app.run(&v1alpha1.Get{}); err != nil {
			log.Error(err.Error())
			os.Exit(1)
		}
	},
}

func init() {
	cmdGet.DisableFlagsInUseLine = true
	rootCmd.AddCommand(cmdGet)
}
