// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"os"

	"github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	"github.com/spf13/cobra"
)

var cmdApply = &cobra.Command{
	Use:   "apply [global flags] -- [apply args]",
	Short: "Run terraform apply",
	PreRun: validatePath,
	Run: func(cmd *cobra.Command, args []string) {
		runApp(&v1alpha1.Apply{}, "apply", DoubleDashArgsHandler(os.Args))
	},
}

func init() {
	cmdApply.DisableFlagsInUseLine = true
	rootCmd.AddCommand(cmdApply)
}
