// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"os"

	"github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	"github.com/spf13/cobra"
)

var cmdGet = &cobra.Command{
	Use:   "get [global flags] -- [get args]",
	Short: "Run terraform get",
	PreRun: validatePath,
	Run: func(cmd *cobra.Command, args []string) {
		runApp(&v1alpha1.Get{}, "get", DoubleDashArgsHandler(os.Args))
	},
}

func init() {
	cmdGet.DisableFlagsInUseLine = true
	rootCmd.AddCommand(cmdGet)
}
