// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"os"

	"github.com/apex/log"
	"github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	"github.com/spf13/cobra"
)

var cmdRefresh = &cobra.Command{
	Use:   "refresh [global flags] -- [refresh args]",
	Short: "Run terraform refresh",
	Run: func(cmd *cobra.Command, args []string) {
		app := newApp("refresh", DoubleDashArgsHandler(os.Args))
		if err := app.run(&v1alpha1.Refresh{}); err != nil {
			log.Error(err.Error())
			os.Exit(1)
		}
	},
}

func init() {
	cmdRefresh.DisableFlagsInUseLine = true
	rootCmd.AddCommand(cmdRefresh)
}
