// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"os"

	"github.com/apex/log"
	"github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	"github.com/spf13/cobra"
)

var cmdShell = &cobra.Command{
	Use:   "shell [global flags] -- [shell args]",
	Short: "Run interactive shell on workspace pod",
	Run: func(cmd *cobra.Command, args []string) {
		app := newApp("shell", ShellWrapDoubleDashArgsHandler(os.Args))
		if err := app.run(&v1alpha1.Shell{}); err != nil {
			log.Error(err.Error())
			os.Exit(1)
		}
	},
}

func init() {
	cmdShell.DisableFlagsInUseLine = true
	rootCmd.AddCommand(cmdShell)
}
