// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"os"

	"github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	"github.com/spf13/cobra"
)

var cmdShow = &cobra.Command{
	Use:   "show [global flags] -- [show args]",
	Short: "Run terraform show",
	Run: func(cmd *cobra.Command, args []string) {
		app := newApp("show", DoubleDashArgsHandler(os.Args))
		app.run(&v1alpha1.Show{})
	},
}

func init() {
	cmdShow.DisableFlagsInUseLine = true
	rootCmd.AddCommand(cmdShow)
}
