// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"os"

	"github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	"github.com/spf13/cobra"
)

var cmdShell = &cobra.Command{
	Use:   "shell [global flags] -- [shell args]",
	Short: "Run interactive shell on workspace pod",
	PreRun: validatePath,
	Run: func(cmd *cobra.Command, args []string) {
		runApp(&v1alpha1.Shell{}, "shell", ShellWrapDoubleDashArgsHandler(os.Args))
	},
}

func init() {
	cmdShell.DisableFlagsInUseLine = true
	rootCmd.AddCommand(cmdShell)
}
