// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"os"

	"github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	"github.com/spf13/cobra"
)

var cmdRefresh = &cobra.Command{
	Use:   "refresh [global flags] -- [refresh args]",
	Short: "Run terraform refresh",
	Run: func(cmd *cobra.Command, args []string) {
		app := newApp("refresh", DoubleDashArgsHandler(os.Args))
		app.run(&v1alpha1.Refresh{})
	},
}

func init() {
	cmdRefresh.DisableFlagsInUseLine = true
	rootCmd.AddCommand(cmdRefresh)
}
