// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"os"

	"github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	"github.com/spf13/cobra"
)

var cmdInit = &cobra.Command{
	Use:   "init [global flags] -- [init args]",
	Short: "Run terraform init",
	Run: func(cmd *cobra.Command, args []string) {
		app := newApp("init", DoubleDashArgsHandler(os.Args))
		app.run(&v1alpha1.Init{})
	},
}

func init() {
	cmdInit.DisableFlagsInUseLine = true
	rootCmd.AddCommand(cmdInit)
}
