// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"os"

	"github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	"github.com/spf13/cobra"
)

var cmdUntaint = &cobra.Command{
	Use:   "untaint [flags] -- [untaint args]",
	Short: "Run terraform untaint",
	Run: func(cmd *cobra.Command, args []string) {
		runApp(&v1alpha1.Untaint{}, "untaint", DoubleDashArgsHandler(os.Args))
	},
}

func init() {
	rootCmd.AddCommand(cmdUntaint)
}
