// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"os"

	"github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	"github.com/spf13/cobra"
)

var cmdShow = &cobra.Command{
	Use:   "show [flags] -- [show args]",
	Short: "Run terraform show",
	Run: func(cmd *cobra.Command, args []string) {
		runApp(&v1alpha1.Show{}, "show", DoubleDashArgsHandler(os.Args))
	},
}

func init() {
	rootCmd.AddCommand(cmdShow)
}
