// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"os"

	"github.com/apex/log"
	"github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	"github.com/spf13/cobra"
)

var cmdForceUnlock = &cobra.Command{
	Use:   "force-unlock [global flags] -- [force-unlock args]",
	Short: "Run terraform force-unlock",
	Run: func(cmd *cobra.Command, args []string) {
		app := newApp("force-unlock", DoubleDashArgsHandler(os.Args))
		if err := app.run(&v1alpha1.ForceUnlock{}); err != nil {
			log.Error(err.Error())
			os.Exit(1)
		}
	},
}

func init() {
	cmdForceUnlock.DisableFlagsInUseLine = true
	rootCmd.AddCommand(cmdForceUnlock)
}
