// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"os"

	"github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	"github.com/spf13/cobra"
)

var cmdDestroy = &cobra.Command{
	Use:   "destroy [flags] -- [destroy args]",
	Short: "Run terraform destroy",
	Run: func(cmd *cobra.Command, args []string) {
		runApp(&v1alpha1.Destroy{}, "destroy", DoubleDashArgsHandler(os.Args))
	},
}

func init() {
	rootCmd.AddCommand(cmdDestroy)
}
