// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"os"

	"github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	"github.com/spf13/cobra"
)

var cmdOutput = &cobra.Command{
	Use:   "output [global flags] -- [output args]",
	Short: "Run terraform output",
	
	Run: func(cmd *cobra.Command, args []string) {
		runApp(&v1alpha1.Output{}, "output", DoubleDashArgsHandler(os.Args))
	},
}

func init() {
	cmdOutput.DisableFlagsInUseLine = true
	rootCmd.AddCommand(cmdOutput)
}
