// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"os"

	"github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	"github.com/spf13/cobra"
)

var cmdTaint = &cobra.Command{
	Use:   "taint [global flags] -- [taint args]",
	Short: "Run terraform taint",
	Run: func(cmd *cobra.Command, args []string) {
		app := newApp("taint", DoubleDashArgsHandler(os.Args))
		app.run(&v1alpha1.Taint{})
	},
}

func init() {
	cmdTaint.DisableFlagsInUseLine = true
	rootCmd.AddCommand(cmdTaint)
}
