// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"os"

	"github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	"github.com/spf13/cobra"
)

var cmdVersion = &cobra.Command{
	Use:   "version [flags] -- [version args]",
	Short: "Run terraform version",
	Run: func(cmd *cobra.Command, args []string) {
		runApp(&v1alpha1.Version{}, "version", DoubleDashArgsHandler(os.Args))
	},
}

func init() {
	rootCmd.AddCommand(cmdVersion)
}
