// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"os"

	"github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	"github.com/spf13/cobra"
)

var cmdTaint = &cobra.Command{
	Use:   "taint [flags] -- [taint args]",
	Short: "Run terraform taint",
	Run: func(cmd *cobra.Command, args []string) {
		runApp(&v1alpha1.Taint{}, "taint", DoubleDashArgsHandler(os.Args))
	},
}

func init() {
	rootCmd.AddCommand(cmdTaint)
}
