// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"os"

	"github.com/apex/log"
	"github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	"github.com/spf13/cobra"
)

var cmdUntaint = &cobra.Command{
	Use:   "untaint [global flags] -- [untaint args]",
	Short: "Run terraform untaint",
	Run: func(cmd *cobra.Command, args []string) {
		app := newApp("untaint", DoubleDashArgsHandler(os.Args))
		if err := app.run(&v1alpha1.Untaint{}); err != nil {
			log.Error(err.Error())
			os.Exit(1)
		}
	},
}

func init() {
	cmdUntaint.DisableFlagsInUseLine = true
	rootCmd.AddCommand(cmdUntaint)
}
