// +build ignore

package main

import (
	"fmt"

	"github.com/iancoleman/strcase"
	"github.com/leg100/stok/crdinfo"
	"github.com/leg100/stok/util"
)

func main() {
	for k, v := range crdinfo.Inventory {
		util.GenerateTemplate(v, cobraCommand, fmt.Sprintf("command_%s.go", strcase.ToSnake(k)))
	}
}

var cobraCommand = `// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"os"

	"github.com/apex/log"
	"github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	"github.com/spf13/cobra"
)

var cmd{{ .Name | ToCamel }} = &cobra.Command{
	Use:   "{{ .Name }} [global flags] -- [{{ .Name }} args]",
	Short: "{{ if ne .Description "" }}{{ .Description }}{{ else }}Run terraform {{ .Name }}{{ end }}",
	Run: func(cmd *cobra.Command, args []string) {
		app := newApp("{{ .Name }}", {{ .ArgsHandler }}(os.Args))
		if err := app.run(&v1alpha1.{{ .Kind | ToCamel }}{}); err != nil {
			log.Error(err.Error())
			os.Exit(1)
		}
	},
}

func init() {
	cmd{{ .Name | ToCamel }}.DisableFlagsInUseLine = true
	rootCmd.AddCommand(cmd{{ .Name | ToCamel }})
}
`
