// Code generated by go generate; DO NOT EDIT.
package queue

import (
	"context"

	"github.com/leg100/stok/pkg/apis/stok/v1alpha1"
	"github.com/operator-framework/operator-sdk/pkg/status"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

func init() {
	// AddToManagerFuncs is a list of functions to create controllers and add them to a manager.
	AddToQueueFuncs = append(AddToQueueFuncs, InitQueueBuilder)
}

func InitQueueBuilder(cl client.Client, workspace, namespace string) ([]string, error) {
	var queue []string
	cmdList := v1alpha1.InitList{}
	err := cl.List(context.TODO(), &cmdList, client.InNamespace(namespace), client.MatchingLabels{
		"workspace": workspace,
	})
	if err != nil {
		return nil, err
	}

	// filter out completed
	for _, cmd := range cmdList.Items {
		if cmd.CommandStatus.Conditions.IsTrueFor(status.ConditionType("Completed")) {
			continue
		}
		queue = append(queue, cmd.GetName())
	}
	return queue, nil
}
